version: 2.1
jobs:
  Hello-World:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  I-Have-Code:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
  Run-With-Python:
    docker:
      - image: circleci/python:3.6.10-node-browsers
    steps:
      - run:
          name: Running in a Unique Container
          command: |
            python --version
  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'
            
workflows:
  version: 2
  Example_Workflow:
    jobs:
      - Hello-World
      - I-Have-Code:
          requires:
            - Hello-World
      - Run-With-Python:
          requires:
            - Hello-World
      - Hold-For-Approval:
          type: approval
          requires:
            - I-Have-Code
            - Run-With-Python
      - Now-Complete:
          requires:
            - Hold-For-Approval
